/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import getRouteFromAssetPath from 'next/dist/shared/lib/router/utils/get-route-from-asset-path';
import { getNamedRouteRegex } from 'next/dist/shared/lib/router/utils/route-regex';
import { clientsClaim } from 'workbox-core';
import type { RouteHandlerCallback } from 'workbox-core/types';
import { ExpirationPlugin } from 'workbox-expiration';
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  cleanupOutdatedCaches,
} from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
const precacheEntries = self.__WB_MANIFEST;
precacheAndRoute(precacheEntries);

cleanupOutdatedCaches();

// Set up App Shell-style routing for Next.js export which generates an
// HTML file per route, so that all navigation requests to the route
// (derived from the file name) are fulfilled with that HTML file shell.
// Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const dynamicPageHandlers = precacheEntries.reduce((acc, e) => {
  if (typeof e === 'string') return acc;

  if (e.url.endsWith('.html')) {
    acc.push([
      // Converts e.g. /train/[...train].html to
      // RegExp /^\\/train\\/(.+?)(?:\\/)?$/
      getNamedRouteRegex(getRouteFromAssetPath(e.url, '.html'), true).re,
      createHandlerBoundToURL(e.url),
    ]);
  }

  return acc;
}, [] as [RegExp, RouteHandlerCallback][]);

dynamicPageHandlers.forEach(([exp, handler]) => {
  registerRoute(({ url }: { request: Request; url: URL }) => {
    return exp.test(url.pathname);
  }, handler);
});

// Google fonts
registerRoute(
  new RegExp('https://fonts.(?:googleapis|gstatic).com/(.*)'),
  new StaleWhileRevalidate({
    cacheName: 'google-fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 20 })],
  })
);

// MapLibre GL JS css (from unpkg)
registerRoute(new RegExp('https://unpkg.com/(.*)'), new StaleWhileRevalidate());

// Same-origin image requests
registerRoute(
  ({ sameOrigin, request }) => sameOrigin && request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// Same-origin static data assets
registerRoute(
  /\.(json)$/i,
  new NetworkFirst({
    cacheName: 'static-data-assets',
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
